import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "../components/navigation/SiteHeader";
import SoundBtn from "../components/ui/SoundBtn";
import LenisProvider from "../components/ui/LenisProvider";
import FloatingSectionControls from "../components/navigation/FloatingSectionControls";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function GlobalSoundToggle() {
  return (
    <div className="fixed bottom-6 left-6 z-50 hidden md:block">
      <SoundBtn />
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider />
        <SiteHeader />
        <GlobalSoundToggle />
        <FloatingSectionControls />

        {children}
        <Analytics />
      </body>
    </html>
  );
}
